name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
          cache: true
      - name: Install dependencies
        run: go get ./...
      - name: Build
        run: go build -v ./...
      - name: Run coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...
      - name: Run e2e
        run: |
          go install ./...
          git config --global url.https://github.com/.insteadOf git://github.com/
          git clone https://github.com/adevinta/vulcan-checks.git
          vulcan-check-catalog -registry-url "example.com" -tag "stable" vulcan-checks/cmd/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
